version: '3.1'

services:
  rabbitmq-new:
    container_name: rabbitmq_3
    image: rabbitmq:3-management
    restart: always
    ports:
      - "7892:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: mq_user
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_VHOST: /testvhost

